// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB73EGGLMhwyFMCWMnc1w-QbkVYKRayY68',
    appId: '1:652344936365:web:ab035b860c5a0e76d94324',
    messagingSenderId: '652344936365',
    projectId: 'shopelec-d93e6',
    authDomain: 'shopelec-d93e6.firebaseapp.com',
    storageBucket: 'shopelec-d93e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOCCNQKCk7XEoUVK_M8R8iQ-JKt5zGEPA',
    appId: '1:652344936365:android:fedde12f05b0f874d94324',
    messagingSenderId: '652344936365',
    projectId: 'shopelec-d93e6',
    storageBucket: 'shopelec-d93e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaJXzlw0NHjYN3GeJd2-UPt5GNKsUCNio',
    appId: '1:652344936365:ios:9caecc167d31a497d94324',
    messagingSenderId: '652344936365',
    projectId: 'shopelec-d93e6',
    storageBucket: 'shopelec-d93e6.appspot.com',
    iosBundleId: 'com.example.shopelec',
  );
}
